### ISSUE TITLE
Confusion about the loss curve plot and random seeds

### ISSUE THREAD

**Issue by xxdznl** [haozzh/FedCR#5]
@haozzh hello!

1. The loss of my FedCR reproduction results（or any other methods） on **CIFAR100-Dirichlet settings** initially decreases and then increases but the test accuracy keeps improving, which is contrary to common sense.  Could you please upload the loss curve plot of your results? Do you have the same issue? and if so, could you please provide a reasonable explanation for it?
2. Additionally, apart from the seed 23, what are the values of the other two random seeds you used?

**Comment by haozzh** [comment]
1. To begin, I would like to emphasize that our primary focus in PFL is centered around the variations in average generalization accuracy rather than the loss values. According to your results, it is conceivable that the loss for certain nodes experiences a more substantial increase while their corresponding accuracy decreases at a relatively modest rate. Conversely, for other nodes, their loss might decrease only marginally, yet their accuracy registers a notable increase. In the process of computing the overall average loss, there could be instances where the total loss increases, but intriguingly, the accuracy still demonstrates an upward trajectory.
2. There are no constraints on the selection of random seeds; in fact, we employed a variety of seeds, including 200 and 100, among others.

**Comment by xxdznl** [comment]
> 1. To begin, I would like to emphasize that our primary focus in PFL is centered around the variations in average generalization accuracy rather than the loss values. According to your results, it is conceivable that the loss for certain nodes experiences a more substantial increase while their corresponding accuracy decreases at a relatively modest rate. Conversely, for other nodes, their loss might decrease only marginally, yet their accuracy registers a notable increase. In the process of computing the overall average loss, there could be instances where the total loss increases, but intriguingly, the accuracy still demonstrates an upward trajectory.
> 2. There are no constraints on the selection of random seeds; in fact, we employed a variety of seeds, including 200 and 100, among others.
Thank you very much for your answer。

**Comment by xxdznl** [comment]
Thank you very much for your answer.
